"""esquema inicial P2

Revision ID: dd6986e58c40
Revises: 
Create Date: 2026-10-02 16:38:22.779771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd6986e58c40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('document_id', sa.String(length=60), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('budget_preference', sa.String(length=80), nullable=True),
    sa.Column('preferred_destinations', sa.JSON(), nullable=True),
    sa.Column('trips_count', sa.Integer(), nullable=True),
    sa.Column('total_spent', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('passport_expiry', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_clients_status'), ['status'], unique=False)

    op.create_table('destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weather_type', sa.String(length=60), nullable=True),
    sa.Column('best_season', sa.String(length=60), nullable=True),
    sa.Column('high_season_months', sa.JSON(), nullable=True),
    sa.Column('popular_attractions', sa.JSON(), nullable=True),
    sa.Column('base_price_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_destinations_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_destinations_status'), ['status'], unique=False)

    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('airline', sa.String(length=120), nullable=True),
    sa.Column('flight_number', sa.String(length=30), nullable=True),
    sa.Column('origin', sa.String(length=120), nullable=True),
    sa.Column('destination', sa.String(length=120), nullable=True),
    sa.Column('departure_time', sa.String(length=40), nullable=True),
    sa.Column('arrival_time', sa.String(length=40), nullable=True),
    sa.Column('price_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('seats_available', sa.Integer(), nullable=True),
    sa.Column('total_seats', sa.Integer(), nullable=True),
    sa.Column('flight_class', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('baggage_allowance', sa.String(length=80), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flights_airline'), ['airline'], unique=False)
        batch_op.create_index(batch_op.f('ix_flights_flight_number'), ['flight_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_flights_status'), ['status'], unique=False)

    op.create_table('ncf_sequences',
    sa.Column('prefix', sa.String(length=8), nullable=False),
    sa.Column('current', sa.Integer(), nullable=False),
    sa.Column('max_number', sa.Integer(), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('prefix')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('date', sa.String(length=40), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('link_tab', sa.String(length=40), nullable=True),
    sa.Column('visible_roles', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('discount_percentage', sa.Integer(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('current_uses', sa.Integer(), nullable=True),
    sa.Column('applicable_categories', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promotions_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotions_code'), ['code'], unique=True)

    op.create_table('settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('transports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=True),
    sa.Column('route', sa.String(length=160), nullable=True),
    sa.Column('vehicle_model', sa.String(length=120), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('available_seats', sa.Integer(), nullable=True),
    sa.Column('driver_name', sa.String(length=120), nullable=True),
    sa.Column('price_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transports_status'), ['status'], unique=False)

    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('destination_name', sa.String(length=160), nullable=True),
    sa.Column('duration_hours', sa.Integer(), nullable=True),
    sa.Column('price_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('includes_guide', sa.Boolean(), nullable=True),
    sa.Column('difficulty', sa.String(length=40), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('schedule', sa.String(length=120), nullable=True),
    sa.Column('includes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_destination_name'), ['destination_name'], unique=False)

    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('destination_name', sa.String(length=160), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('contact_phone', sa.String(length=40), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hotels_destination_name'), ['destination_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_hotels_name'), ['name'], unique=False)

    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('destination_name', sa.String(length=160), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('duration_nights', sa.Integer(), nullable=True),
    sa.Column('price_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('original_price_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('available_slots', sa.Integer(), nullable=True),
    sa.Column('total_slots', sa.Integer(), nullable=True),
    sa.Column('max_capacity', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('gallery', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.Column('inclusions', sa.JSON(), nullable=True),
    sa.Column('itinerary_summary', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('departure_dates', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packages_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_packages_destination_name'), ['destination_name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('google_id', sa.String(length=120), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=120), nullable=True),
    sa.Column('user_role', sa.String(length=20), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=True),
    sa.Column('module', sa.String(length=80), nullable=True),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.String(length=60), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('notification_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_id', 'user_id', name='uq_notification_user')
    )
    with op.batch_alter_table('notification_reads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_reads_notification_id'), ['notification_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_reads_user_id'), ['user_id'], unique=False)

    op.create_table('room_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('price_per_night', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rooms_total', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_types_hotel_id'), ['hotel_id'], unique=False)

    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_code', sa.String(length=30), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('package_name', sa.String(length=200), nullable=True),
    sa.Column('destination_name', sa.String(length=160), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('hotel_name', sa.String(length=200), nullable=True),
    sa.Column('room_type_id', sa.Integer(), nullable=True),
    sa.Column('rooms_count', sa.Integer(), nullable=True),
    sa.Column('check_in', sa.Date(), nullable=True),
    sa.Column('check_out', sa.Date(), nullable=True),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('flight_number', sa.String(length=30), nullable=True),
    sa.Column('transport_id', sa.Integer(), nullable=True),
    sa.Column('departure_date', sa.Date(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('travelers', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ),
    sa.ForeignKeyConstraint(['transport_id'], ['transports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_booking_code'), ['booking_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_bookings_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_destination_name'), ['destination_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_status'), ['status'], unique=False)

    op.create_table('booking_passengers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('document', sa.String(length=60), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_passengers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_passengers_booking_id'), ['booking_id'], unique=False)

    op.create_table('itineraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('destination', sa.String(length=160), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itineraries_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_itineraries_client_id'), ['client_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=True),
    sa.Column('receipt_number', sa.String(length=40), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('ncf', sa.String(length=20), nullable=True),
    sa.Column('invoice_number', sa.String(length=40), nullable=True),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ncf')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_receipt_number'), ['receipt_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)

    op.create_table('promotion_redemptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promotion_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id'),
    sa.UniqueConstraint('promotion_id', 'booking_id', name='uq_promotion_booking')
    )
    with op.batch_alter_table('promotion_redemptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promotion_redemptions_promotion_id'), ['promotion_id'], unique=False)

    op.create_table('travel_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('doc_type', sa.String(length=80), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('stored_name', sa.String(length=255), nullable=True),
    sa.Column('mime', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('upload_date', sa.Date(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('travel_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_travel_documents_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_travel_documents_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_travel_documents_status'))
        batch_op.drop_index(batch_op.f('ix_travel_documents_client_id'))

    op.drop_table('travel_documents')
    with op.batch_alter_table('promotion_redemptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promotion_redemptions_promotion_id'))

    op.drop_table('promotion_redemptions')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_receipt_number'))
        batch_op.drop_index(batch_op.f('ix_payments_created_at'))
        batch_op.drop_index(batch_op.f('ix_payments_booking_id'))

    op.drop_table('payments')
    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itineraries_client_id'))
        batch_op.drop_index(batch_op.f('ix_itineraries_booking_id'))

    op.drop_table('itineraries')
    with op.batch_alter_table('booking_passengers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_passengers_booking_id'))

    op.drop_table('booking_passengers')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_bookings_destination_name'))
        batch_op.drop_index(batch_op.f('ix_bookings_created_at'))
        batch_op.drop_index(batch_op.f('ix_bookings_client_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_booking_code'))

    op.drop_table('bookings')
    with op.batch_alter_table('room_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_types_hotel_id'))

    op.drop_table('room_types')
    with op.batch_alter_table('notification_reads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_reads_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_reads_notification_id'))

    op.drop_table('notification_reads')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_module'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packages_destination_name'))
        batch_op.drop_index(batch_op.f('ix_packages_category'))

    op.drop_table('packages')
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hotels_name'))
        batch_op.drop_index(batch_op.f('ix_hotels_destination_name'))

    op.drop_table('hotels')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_destination_name'))
        batch_op.drop_index(batch_op.f('ix_activities_category'))

    op.drop_table('activities')
    with op.batch_alter_table('transports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transports_status'))

    op.drop_table('transports')
    op.drop_table('settings')
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promotions_code'))
        batch_op.drop_index(batch_op.f('ix_promotions_active'))

    op.drop_table('promotions')
    op.drop_table('notifications')
    op.drop_table('ncf_sequences')
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flights_status'))
        batch_op.drop_index(batch_op.f('ix_flights_flight_number'))
        batch_op.drop_index(batch_op.f('ix_flights_airline'))

    op.drop_table('flights')
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_destinations_status'))
        batch_op.drop_index(batch_op.f('ix_destinations_name'))

    op.drop_table('destinations')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_status'))
        batch_op.drop_index(batch_op.f('ix_clients_email'))
        batch_op.drop_index(batch_op.f('ix_clients_created_at'))

    op.drop_table('clients')
    # ### end Alembic commands ###
